name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        configuration: ['debug', 'release']
    runs-on: macOS-14
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '^15.2.0'
    - uses: actions/checkout@v4
    - run: swift build -c ${{ matrix.configuration }} -Xswiftc -enable-testing
  podspec:
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
        platform: ['ios', 'macos']
    runs-on: macOS-14
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '^15.2.0'
    - uses: actions/checkout@v4
    - run: bundle install
    - run: bundle exec pod lib lint --platforms=${{ matrix.platform }} --configuration=${{ matrix.configuration }}
